language: generic

matrix:
  include:

    # macOS Python 2
    - os: osx
      env:
          PYTHON=python2
          PIP=pip2
      before_install:
        - brew update
        # - brew cask uninstall oclint # Workaround for upgrading gcc, see https://github.com/travis-ci/travis-ci/issues/8826
        - brew outdated python || brew upgrade python

    # macOS Python 3
    - os: osx
      env:
          PYTHON=python3
          PIP=pip2
      before_install:
        - brew update
        # - brew cask uninstall oclint # Workaround for upgrading gcc, see https://github.com/travis-ci/travis-ci/issues/8826
        - brew outdated python || brew upgrade python

install:
    $PYTHON -m pip install -r requirements.txt

script:
    $PYTHON setup.py test

after_success:
    $PYTHON setup.py bdist_wheel

before_deploy:
    $PYTHON -m pip install twine

deploy:
  - provider: script
    skip_cleanup: true
    script: twine upload dist/*.whl --username $PYPI_USER --password $PYPI_PASSWORD
    on:
      tags: true
