language: python

matrix:
    include:
        - sudo: required
            services:
                - docker
            env: PIP=pip
        - os: osx
            language: generic
            env: PIP=pip2

python:
  - "2.7"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install .

script:
  - $PIP install cibuildwheel==0.10.0
  - cibuildwheel --output-dir wheelhouse

# command to run tests
script:
    pytest
