# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2

jobs:
  test:
    docker:
      - image: circleci/python:3.6

    environment:
      PYTHON: python

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Prepare the enviornment.
          command: |
            bash .circleci/prepare.sh

#      - run:
#          name: Test
#          command: |
#            venv/bin/python -m pytest ./hazma/test/

  build:
    v
    docker:
      - image: circleci/python:3.6

    environment:
      PYTHON: python

    steps:
      - checkout
      - setup_remote_docker

      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages

      - run:
          name: Prepare the enviornment.
          command: |
            bash .circleci/prepare.sh

      # Build Linux wheels
      - run:
          name: Build the Linux wheeels
          command: |
            sudo chown -R circleci:circleci venv/bin
            venv/bin/activate
            ci build
#            venv/bin/python -m pip install cibuildwheel
#            cibuildwheel --output-dir wheelhouse

      - store_artifacts:
          path: wheelhouse/

#   osx-test-and-wheels:
#     working_directory: ~/osx-wheels
#     # Get xcode
#     macos:
#      xcode: "10.0.0"
#    steps:
#      - checkout
#      - restore_cache:
#        keys:
#          - v1-dependencies-{{ checksum "requirements.txt" }}
#          # fallback to using the latest cache if no exact match is found
#          - v1-dependencies-
#      # Install depndencies from requirements.txt
#      - run:
#        name: install dependencies
#        command: |
#          pip install -r requirements.txt
#          pip install --upgrade .
#      - save_cache:
#        paths:
#          - ./venv
#        key: v1-dependencies-{{ checksum "requirements.txt" }}
#      # run tests!
#      - run:
#        name: run tests
#        command: |
#          py.test ./hazma/test/
#      # Build OS X wheels
#      - run:
#        name: Build the OS X wheels
#        command: |
#          pip install --user cibuildwheel
#          cibuildwheel --output-dir wheelhouse
#      - store_artifacts:
#        path: wheelhouse/

workflows:
  version: 2
  all-tests:
    jobs:
      - test
      - build
#      - osx-test-and-wheels





#git clone https://github.com/pyenv/pyenv.git ~/.pyenv
#echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bash_profile
#echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bash_profile
#echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.bash_profile
#source ~/.bash_profile

#pyenv install 2.7.13
#pyenv global 2.7.13
