version: 2

jobs:
  build-2.7: &build_template
    docker:
      - image: circleci/python:2.7
        user: root
    steps:
      - checkout
      - setup_remote_docker

      - attach_workspace:
          at: /hazma
      - run:
          name: Prepare the environment.
          command: |
            bash .circleci/prepare.sh
      - run:
          name: Test.
          command: |
            venv/bin/python setup.py test
      - run:
          name: Build Distribution
          command: venv/bin/python setup.py bdist_wheel
      - persist_to_workspace:
          root: .
          paths: dist

  build-3.6:
      <<: *build_template
    docker:
      - image: circleci/python:3.6
        user: root

workflows:
  version: 2
  all-tests:
    jobs:
      - build-2.7
      - build-3.6
