version: 2

env:
  global:
    - CIBW_TEST_REQUIRES=pip>=9.0.1 scipy>=1.0.0 numpy==1.13.3 cython==0.27.3 scikit-image==0.14.0 setuptools==27.3

jobs:
  build-2.7: &build_template
    docker:
      - image: circleci/python:2.7
        user: root
    environment:
      PYTHON: python2
    steps:
      - checkout
      - setup_remote_docker

      - attach_workspace:
          at: /hazma
      - run:
          name: Prepare the environment.
          command: |
            bash .circleci/prepare.sh
      - run:
          name: Test.
          command: |
            venv/bin/python setup.py test
      - run:
          name: Build Distribution
          command: |
            venv/bin/cibuildwheel --output-dir dist
      - persist_to_workspace:
          root: .
          paths: dist

  build-3.6:
    <<: *build_template
    docker:
      - image: circleci/python:3.6
        user: root
    environment:
      PYTHON: python3

workflows:
  version: 2
  all-tests:
    jobs:
      - build-2.7
      - build-3.6
