# To test:
# docker pull circleci/picard
# docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):$(pwd) -v ~/.circleci/:/root/.circleci --workdir $(pwd) circleci/picard circleci build

version: 2
jobs:
  build-3.7: &build_template
    working_directory: /hazma
    docker:
      - image: circleci/python:3.7
        user: root
    steps:
      - checkout
      - attach_workspace:
          at: /hazma
      - run:
          name: Setup SciKit-CI
          command: |
            pip install scikit-ci==0.13.0 scikit-ci-addons==0.11.0
            ci_addons --install ../addons
      - run:
          name: Install
          command: ci install
      - run:
          name: Test
          command: ci test
      - run:
          name: Build Distribution
          command: ci after_test
      - persist_to_workspace:
          root: .
          paths: dist

  build-3.6:
    <<: *build_template
    docker:
      - image: circleci/python:3.6
        user: root

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-3.7: &build_job_template
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
      - build-3.6:
          <<: *build_job_template
