version: 2

jobs:
  linux-python2:
    docker:
      - image: circleci/python:2.7
        user: root
    environment:
      PYTHON: python2
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Prepare the environment.
          command: |
            bash .circleci/prepare.sh
      - run:
          name: Test.
          command: |
            venv/bin/python setup.py test
  linux-python3:
    docker:
      - image: circleci/python:3.6
        user: root
    environment:
      PYTHON: python3
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Prepare the environment.
          command: |
            bash .circleci/prepare.sh
      - run:
          name: Test.
          command: |
            venv/bin/python setup.py test
workflows:
  version: 2
  all-tests:
    jobs:
      - linux-python2
      - linux-python3
